//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito_det
    {
        public int cons_carrito_det { get; set; }
        public int cons_carrito { get; set; }
        public int cons_producto { get; set; }
        public int cantidad { get; set; }
    
        public virtual carrito_enc carrito_enc { get; set; }
        public virtual productos productos { get; set; }
    }
}
