//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.MASCOTAS = new HashSet<MASCOTAS>();
            this.VENTAS_CLIENTES_ENC = new HashSet<VENTAS_CLIENTES_ENC>();
        }
    
        public long ID_CLIENTE { get; set; }
        public long ID_USUARIO { get; set; }
        public string NUM_IDENTIFIC_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASCOTAS> MASCOTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS_CLIENTES_ENC> VENTAS_CLIENTES_ENC { get; set; }
    }
}
