//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS_PROVEEDORES_ENC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRAS_PROVEEDORES_ENC()
        {
            this.COMPRAS_PROVEEDORES_DET = new HashSet<COMPRAS_PROVEEDORES_DET>();
        }
    
        public long ID_COMPRA { get; set; }
        public long ID_PROVEEDOR { get; set; }
        public System.DateTime FEC_COMPRA { get; set; }
        public decimal MONTO_COMPRA_BRUT { get; set; }
        public decimal IMPUESTO_COMPRA_TOT { get; set; }
        public decimal MONTO_COMPRA_NET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS_PROVEEDORES_DET> COMPRAS_PROVEEDORES_DET { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
