//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS_PROVEEDORES_DET
    {
        public long ID_COMPRA_DET { get; set; }
        public long ID_COMPRA { get; set; }
        public long ID_PRODUCTO { get; set; }
        public long ID_UNIDAD_MEDIDA { get; set; }
        public int CANTIDAD { get; set; }
        public decimal MONTO_LINEA { get; set; }
        public decimal IMPUESTO_LINEA { get; set; }
        public decimal MONTO_NETO_LINEA { get; set; }
    
        public virtual COMPRAS_PROVEEDORES_ENC COMPRAS_PROVEEDORES_ENC { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
    }
}
