//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS_PROVEEDORES_ENC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRAS_PROVEEDORES_ENC()
        {
            this.COMPRAS_PROVEEDORES_DET = new HashSet<COMPRAS_PROVEEDORES_DET>();
        }
    
        public long ID_COMPRA { get; set; }
        public long ID_PROVEEDOR { get; set; }
        public System.DateTime FEC_COMPRA { get; set; }
        public decimal MONTO_COMPRA_BRUT { get; set; }
        public decimal IMPUESTO_COMPRA_TOT { get; set; }
        public decimal MONTO_COMPRA_NET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS_PROVEEDORES_DET> COMPRAS_PROVEEDORES_DET { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
