//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAS_PROVEEDORES_DET
    {
        public long ID_COMPRA_DET { get; set; }
        public long ID_COMPRA { get; set; }
        public long ID_PRODUCTO { get; set; }
        public long ID_UNIDAD_MEDIDA { get; set; }
        public int CANTIDAD { get; set; }
        public decimal MONTO_LINEA { get; set; }
        public decimal IMPUESTO_LINEA { get; set; }
        public decimal MONTO_NETO_LINEA { get; set; }
    
        public virtual COMPRAS_PROVEEDORES_ENC COMPRAS_PROVEEDORES_ENC { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
    }
}
