//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUA_PROV
    {
        public long ID_EVALUA_PROV { get; set; }
        public string DESCRIPCION { get; set; }
        public long ID_VENTA_DET { get; set; }
    
        public virtual VENTAS_CLIENTES_DET VENTAS_CLIENTES_DET { get; set; }
    }
}
