//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_det
    {
        public int cons_inventario_det { get; set; }
        public int consec_producto { get; set; }
        public int cons_inventario { get; set; }
        public int cantidad_inventario { get; set; }
    
        public virtual inventario_enc inventario_enc { get; set; }
        public virtual productos productos { get; set; }
    }
}
