//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_det
    {
        public int cons_inventario_det { get; set; }
        public int consec_producto { get; set; }
        public int cons_inventario { get; set; }
        public int cantidad_inventario { get; set; }
    
        public virtual inventario_enc inventario_enc { get; set; }
        public virtual productos productos { get; set; }
    }
}
