//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_DET
    {
        public long ID_INVENTARIO_DET { get; set; }
        public long ID_PRODUCTO { get; set; }
        public long ID_UNI_MEDIDA { get; set; }
        public long ID_INVENTARIO { get; set; }
        public int CANTIDAD_INVENTARIO { get; set; }
    
        public virtual INVENTARIO_ENC INVENTARIO_ENC { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
    }
}
