//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_enc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario_enc()
        {
            this.inventario_det = new HashSet<inventario_det>();
        }
    
        public int cons_inventario { get; set; }
        public System.DateTime fec_inventario { get; set; }
        public string observaciones { get; set; }
        public string estado_inv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_det> inventario_det { get; set; }
    }
}
