//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTAS
    {
        public long ID_MASCOTA { get; set; }
        public long ID_RAZA { get; set; }
        public long ID_CLIENTE { get; set; }
        public string NOMBRE_MASCOTA { get; set; }
        public Nullable<System.DateTime> FEC_NACIMIENTO { get; set; }
        public string COLOR_PELAJE { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual RAZAS RAZAS { get; set; }
    }
}
