//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASCOTAS
    {
        public long ID_MASCOTA { get; set; }
        public long ID_RAZA { get; set; }
        public long ID_CLIENTE { get; set; }
        public string NOMBRE_MASCOTA { get; set; }
        public Nullable<System.DateTime> FEC_NACIMIENTO { get; set; }
        public string COLOR_PELAJE { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual RAZAS RAZAS { get; set; }
    }
}
