//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WaggyEntities : DbContext
    {
        public WaggyEntities()
            : base("name=WaggyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COMPRAS_PROVEEDORES_DET> COMPRAS_PROVEEDORES_DET { get; set; }
        public virtual DbSet<COMPRAS_PROVEEDORES_ENC> COMPRAS_PROVEEDORES_ENC { get; set; }
        public virtual DbSet<EVALUA_PROV> EVALUA_PROV { get; set; }
        public virtual DbSet<INVENTARIO_DET> INVENTARIO_DET { get; set; }
        public virtual DbSet<INVENTARIO_ENC> INVENTARIO_ENC { get; set; }
        public virtual DbSet<MASCOTAS> MASCOTAS { get; set; }
        public virtual DbSet<PRODUCTO_PROVEED> PRODUCTO_PROVEED { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public virtual DbSet<RAZAS> RAZAS { get; set; }
        public virtual DbSet<UNIDAD_MEDIDA> UNIDAD_MEDIDA { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<VENTAS_CLIENTES_DET> VENTAS_CLIENTES_DET { get; set; }
        public virtual DbSet<VENTAS_CLIENTES_ENC> VENTAS_CLIENTES_ENC { get; set; }
    
        public virtual int RegistrarUsuario(string identificacion, string password, string nombre, string correo)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarUsuario", identificacionParameter, passwordParameter, nombreParameter, correoParameter);
        }
    
        public virtual int sp_RegistrarUsuario(string identificacion, string nombre, string correo, string password)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuario", identificacionParameter, nombreParameter, correoParameter, passwordParameter);
        }
    
        public virtual int sp_RegistroUsuario(string identificacion, string nombre, string correo, string password)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistroUsuario", identificacionParameter, nombreParameter, correoParameter, passwordParameter);
        }
    }
}
