//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WaggyDBEntities : DbContext
    {
        public WaggyDBEntities()
            : base("name=WaggyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<inventario_det> inventario_det { get; set; }
        public virtual DbSet<inventario_enc> inventario_enc { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ventas_clientes_det> ventas_clientes_det { get; set; }
        public virtual DbSet<ventas_clientes_enc> ventas_clientes_enc { get; set; }
    
        public virtual int sp_ActualizaContrasenna(string contrasenna, Nullable<int> consecutivo)
        {
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizaContrasenna", contrasennaParameter, consecutivoParameter);
        }
    
        public virtual int sp_ActualizarContrasenna(string contrasenna, Nullable<int> consecutivo)
        {
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarContrasenna", contrasennaParameter, consecutivoParameter);
        }
    
        public virtual int sp_AlternarEstadoProducto(Nullable<int> cONS_PRODUCTO)
        {
            var cONS_PRODUCTOParameter = cONS_PRODUCTO.HasValue ?
                new ObjectParameter("CONS_PRODUCTO", cONS_PRODUCTO) :
                new ObjectParameter("CONS_PRODUCTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AlternarEstadoProducto", cONS_PRODUCTOParameter);
        }
    
        public virtual int sp_AlternarEstadoUsuario(Nullable<int> consecutivo)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AlternarEstadoUsuario", consecutivoParameter);
        }
    
        public virtual int sp_AplicarInventario(Nullable<int> consInventario)
        {
            var consInventarioParameter = consInventario.HasValue ?
                new ObjectParameter("ConsInventario", consInventario) :
                new ObjectParameter("ConsInventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AplicarInventario", consInventarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_CrearInventarioEnc(Nullable<System.DateTime> fecInventario, string observaciones)
        {
            var fecInventarioParameter = fecInventario.HasValue ?
                new ObjectParameter("FecInventario", fecInventario) :
                new ObjectParameter("FecInventario", typeof(System.DateTime));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_CrearInventarioEnc", fecInventarioParameter, observacionesParameter);
        }
    
        public virtual int sp_CrearProducto(string nOMBRE_PRODUCTO, string dESCRIPCION_PRODUCTO, string iMAGEN, Nullable<decimal> pRECIO, string uNIDAD_MEDIDA, Nullable<int> eXISTENCIA, Nullable<int> eXISTENCIAMIN, Nullable<int> eXISTENCIAMAX, Nullable<int> cONS_CATEGORIA, string tIPO_MASCOTA)
        {
            var nOMBRE_PRODUCTOParameter = nOMBRE_PRODUCTO != null ?
                new ObjectParameter("NOMBRE_PRODUCTO", nOMBRE_PRODUCTO) :
                new ObjectParameter("NOMBRE_PRODUCTO", typeof(string));
    
            var dESCRIPCION_PRODUCTOParameter = dESCRIPCION_PRODUCTO != null ?
                new ObjectParameter("DESCRIPCION_PRODUCTO", dESCRIPCION_PRODUCTO) :
                new ObjectParameter("DESCRIPCION_PRODUCTO", typeof(string));
    
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var uNIDAD_MEDIDAParameter = uNIDAD_MEDIDA != null ?
                new ObjectParameter("UNIDAD_MEDIDA", uNIDAD_MEDIDA) :
                new ObjectParameter("UNIDAD_MEDIDA", typeof(string));
    
            var eXISTENCIAParameter = eXISTENCIA.HasValue ?
                new ObjectParameter("EXISTENCIA", eXISTENCIA) :
                new ObjectParameter("EXISTENCIA", typeof(int));
    
            var eXISTENCIAMINParameter = eXISTENCIAMIN.HasValue ?
                new ObjectParameter("EXISTENCIAMIN", eXISTENCIAMIN) :
                new ObjectParameter("EXISTENCIAMIN", typeof(int));
    
            var eXISTENCIAMAXParameter = eXISTENCIAMAX.HasValue ?
                new ObjectParameter("EXISTENCIAMAX", eXISTENCIAMAX) :
                new ObjectParameter("EXISTENCIAMAX", typeof(int));
    
            var cONS_CATEGORIAParameter = cONS_CATEGORIA.HasValue ?
                new ObjectParameter("CONS_CATEGORIA", cONS_CATEGORIA) :
                new ObjectParameter("CONS_CATEGORIA", typeof(int));
    
            var tIPO_MASCOTAParameter = tIPO_MASCOTA != null ?
                new ObjectParameter("TIPO_MASCOTA", tIPO_MASCOTA) :
                new ObjectParameter("TIPO_MASCOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearProducto", nOMBRE_PRODUCTOParameter, dESCRIPCION_PRODUCTOParameter, iMAGENParameter, pRECIOParameter, uNIDAD_MEDIDAParameter, eXISTENCIAParameter, eXISTENCIAMINParameter, eXISTENCIAMAXParameter, cONS_CATEGORIAParameter, tIPO_MASCOTAParameter);
        }
    
        public virtual int sp_CrearUsuario(string iDENTIFICACION, string nOMBRE, string cORREO, string pASSWORD, string tELEFONO, string dIRECCION, Nullable<int> cONSECUTIVO_ROL)
        {
            var iDENTIFICACIONParameter = iDENTIFICACION != null ?
                new ObjectParameter("IDENTIFICACION", iDENTIFICACION) :
                new ObjectParameter("IDENTIFICACION", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cONSECUTIVO_ROLParameter = cONSECUTIVO_ROL.HasValue ?
                new ObjectParameter("CONSECUTIVO_ROL", cONSECUTIVO_ROL) :
                new ObjectParameter("CONSECUTIVO_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearUsuario", iDENTIFICACIONParameter, nOMBREParameter, cORREOParameter, pASSWORDParameter, tELEFONOParameter, dIRECCIONParameter, cONSECUTIVO_ROLParameter);
        }
    
        public virtual int sp_EditarProducto(Nullable<int> cONS_PRODUCTO, string nOMBRE_PRODUCTO, string dESCRIPCION_PRODUCTO, string iMAGEN, Nullable<decimal> pRECIO, string uNIDAD_MEDIDA, Nullable<int> eXISTENCIA, Nullable<int> eXISTENCIAMIN, Nullable<int> eXISTENCIAMAX, Nullable<int> cONS_CATEGORIA, string tIPO_MASCOTA)
        {
            var cONS_PRODUCTOParameter = cONS_PRODUCTO.HasValue ?
                new ObjectParameter("CONS_PRODUCTO", cONS_PRODUCTO) :
                new ObjectParameter("CONS_PRODUCTO", typeof(int));
    
            var nOMBRE_PRODUCTOParameter = nOMBRE_PRODUCTO != null ?
                new ObjectParameter("NOMBRE_PRODUCTO", nOMBRE_PRODUCTO) :
                new ObjectParameter("NOMBRE_PRODUCTO", typeof(string));
    
            var dESCRIPCION_PRODUCTOParameter = dESCRIPCION_PRODUCTO != null ?
                new ObjectParameter("DESCRIPCION_PRODUCTO", dESCRIPCION_PRODUCTO) :
                new ObjectParameter("DESCRIPCION_PRODUCTO", typeof(string));
    
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var uNIDAD_MEDIDAParameter = uNIDAD_MEDIDA != null ?
                new ObjectParameter("UNIDAD_MEDIDA", uNIDAD_MEDIDA) :
                new ObjectParameter("UNIDAD_MEDIDA", typeof(string));
    
            var eXISTENCIAParameter = eXISTENCIA.HasValue ?
                new ObjectParameter("EXISTENCIA", eXISTENCIA) :
                new ObjectParameter("EXISTENCIA", typeof(int));
    
            var eXISTENCIAMINParameter = eXISTENCIAMIN.HasValue ?
                new ObjectParameter("EXISTENCIAMIN", eXISTENCIAMIN) :
                new ObjectParameter("EXISTENCIAMIN", typeof(int));
    
            var eXISTENCIAMAXParameter = eXISTENCIAMAX.HasValue ?
                new ObjectParameter("EXISTENCIAMAX", eXISTENCIAMAX) :
                new ObjectParameter("EXISTENCIAMAX", typeof(int));
    
            var cONS_CATEGORIAParameter = cONS_CATEGORIA.HasValue ?
                new ObjectParameter("CONS_CATEGORIA", cONS_CATEGORIA) :
                new ObjectParameter("CONS_CATEGORIA", typeof(int));
    
            var tIPO_MASCOTAParameter = tIPO_MASCOTA != null ?
                new ObjectParameter("TIPO_MASCOTA", tIPO_MASCOTA) :
                new ObjectParameter("TIPO_MASCOTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarProducto", cONS_PRODUCTOParameter, nOMBRE_PRODUCTOParameter, dESCRIPCION_PRODUCTOParameter, iMAGENParameter, pRECIOParameter, uNIDAD_MEDIDAParameter, eXISTENCIAParameter, eXISTENCIAMINParameter, eXISTENCIAMAXParameter, cONS_CATEGORIAParameter, tIPO_MASCOTAParameter);
        }
    
        public virtual int sp_EditarUsuario(Nullable<int> consecutivo, string nombre, string telefono, string direccion, Nullable<int> consecutivoRol)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var consecutivoRolParameter = consecutivoRol.HasValue ?
                new ObjectParameter("ConsecutivoRol", consecutivoRol) :
                new ObjectParameter("ConsecutivoRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarUsuario", consecutivoParameter, nombreParameter, telefonoParameter, direccionParameter, consecutivoRolParameter);
        }
    
        public virtual int sp_EliminarInventario(Nullable<int> consInventario)
        {
            var consInventarioParameter = consInventario.HasValue ?
                new ObjectParameter("ConsInventario", consInventario) :
                new ObjectParameter("ConsInventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarInventario", consInventarioParameter);
        }
    
        public virtual int sp_GuardarInventarioDet(Nullable<int> consInventario, Nullable<int> consProducto, Nullable<int> cantidadInventario)
        {
            var consInventarioParameter = consInventario.HasValue ?
                new ObjectParameter("ConsInventario", consInventario) :
                new ObjectParameter("ConsInventario", typeof(int));
    
            var consProductoParameter = consProducto.HasValue ?
                new ObjectParameter("ConsProducto", consProducto) :
                new ObjectParameter("ConsProducto", typeof(int));
    
            var cantidadInventarioParameter = cantidadInventario.HasValue ?
                new ObjectParameter("CantidadInventario", cantidadInventario) :
                new ObjectParameter("CantidadInventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GuardarInventarioDet", consInventarioParameter, consProductoParameter, cantidadInventarioParameter);
        }
    
        public virtual ObjectResult<sp_IniciarSesion_Result> sp_IniciarSesion(string correo, string password)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IniciarSesion_Result>("sp_IniciarSesion", correoParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_ListarProductos_Result> sp_ListarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarProductos_Result>("sp_ListarProductos");
        }
    
        public virtual ObjectResult<sp_ObtenerInventarioDet_Result> sp_ObtenerInventarioDet(Nullable<int> consInventario)
        {
            var consInventarioParameter = consInventario.HasValue ?
                new ObjectParameter("ConsInventario", consInventario) :
                new ObjectParameter("ConsInventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerInventarioDet_Result>("sp_ObtenerInventarioDet", consInventarioParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerInventarios_Result> sp_ObtenerInventarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerInventarios_Result>("sp_ObtenerInventarios");
        }
    
        public virtual ObjectResult<sp_ObtenerProductoPorId_Result> sp_ObtenerProductoPorId(Nullable<int> cONS_PRODUCTO)
        {
            var cONS_PRODUCTOParameter = cONS_PRODUCTO.HasValue ?
                new ObjectParameter("CONS_PRODUCTO", cONS_PRODUCTO) :
                new ObjectParameter("CONS_PRODUCTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerProductoPorId_Result>("sp_ObtenerProductoPorId", cONS_PRODUCTOParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerProductosHomePorCategoria_Result> sp_ObtenerProductosHomePorCategoria(Nullable<int> cONS_CATEGORIA, Nullable<int> cANTIDAD)
        {
            var cONS_CATEGORIAParameter = cONS_CATEGORIA.HasValue ?
                new ObjectParameter("CONS_CATEGORIA", cONS_CATEGORIA) :
                new ObjectParameter("CONS_CATEGORIA", typeof(int));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerProductosHomePorCategoria_Result>("sp_ObtenerProductosHomePorCategoria", cONS_CATEGORIAParameter, cANTIDADParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerUsuarioPorId_Result> sp_ObtenerUsuarioPorId(Nullable<int> consecutivo)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerUsuarioPorId_Result>("sp_ObtenerUsuarioPorId", consecutivoParameter);
        }
    
        public virtual int sp_ValidaCorreo(string correoElectronico)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ValidaCorreo", correoElectronicoParameter);
        }
    
        public virtual ObjectResult<sp_ValidarCorreo_Result> sp_ValidarCorreo(string correoElectronico)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ValidarCorreo_Result>("sp_ValidarCorreo", correoElectronicoParameter);
        }
    }
}
