//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WaggyDBEntities2 : DbContext
    {
        public WaggyDBEntities2()
            : base("name=WaggyDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inventario_det> inventario_det { get; set; }
        public virtual DbSet<inventario_enc> inventario_enc { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<ventas_clientes_det> ventas_clientes_det { get; set; }
        public virtual DbSet<ventas_clientes_enc> ventas_clientes_enc { get; set; }
    
        public virtual int sp_AlternarEstadoUsuario(Nullable<int> consecutivo)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AlternarEstadoUsuario", consecutivoParameter);
        }
    
        public virtual ObjectResult<SP_ConsultarStock_Result> SP_ConsultarStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarStock_Result>("SP_ConsultarStock");
        }
    
        public virtual int sp_CrearUsuario(string iDENTIFICACION, string nOMBRE, string cORREO, string pASSWORD, string tELEFONO, string dIRECCION, Nullable<int> cONSECUTIVO_ROL)
        {
            var iDENTIFICACIONParameter = iDENTIFICACION != null ?
                new ObjectParameter("IDENTIFICACION", iDENTIFICACION) :
                new ObjectParameter("IDENTIFICACION", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cONSECUTIVO_ROLParameter = cONSECUTIVO_ROL.HasValue ?
                new ObjectParameter("CONSECUTIVO_ROL", cONSECUTIVO_ROL) :
                new ObjectParameter("CONSECUTIVO_ROL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearUsuario", iDENTIFICACIONParameter, nOMBREParameter, cORREOParameter, pASSWORDParameter, tELEFONOParameter, dIRECCIONParameter, cONSECUTIVO_ROLParameter);
        }
    
        public virtual int sp_EditarUsuario(Nullable<int> consecutivo, string nombre, string telefono, string direccion, Nullable<int> consecutivoRol)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var consecutivoRolParameter = consecutivoRol.HasValue ?
                new ObjectParameter("ConsecutivoRol", consecutivoRol) :
                new ObjectParameter("ConsecutivoRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditarUsuario", consecutivoParameter, nombreParameter, telefonoParameter, direccionParameter, consecutivoRolParameter);
        }
    
        public virtual int SP_EntradaInventario(Nullable<int> consec_producto, Nullable<int> cantidad)
        {
            var consec_productoParameter = consec_producto.HasValue ?
                new ObjectParameter("consec_producto", consec_producto) :
                new ObjectParameter("consec_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EntradaInventario", consec_productoParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<sp_IniciarSesion_Result> sp_IniciarSesion(string correo, string password)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IniciarSesion_Result>("sp_IniciarSesion", correoParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerUsuarioPorId_Result> sp_ObtenerUsuarioPorId(Nullable<int> consecutivo)
        {
            var consecutivoParameter = consecutivo.HasValue ?
                new ObjectParameter("Consecutivo", consecutivo) :
                new ObjectParameter("Consecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerUsuarioPorId_Result>("sp_ObtenerUsuarioPorId", consecutivoParameter);
        }
    
        public virtual int SP_SalidaInventario(Nullable<int> consec_producto, Nullable<int> cantidad)
        {
            var consec_productoParameter = consec_producto.HasValue ?
                new ObjectParameter("consec_producto", consec_producto) :
                new ObjectParameter("consec_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SalidaInventario", consec_productoParameter, cantidadParameter);
        }
    
        public virtual int SP_RegistrarVenta(Nullable<int> cons_producto, Nullable<int> cantidad)
        {
            var cons_productoParameter = cons_producto.HasValue ?
                new ObjectParameter("cons_producto", cons_producto) :
                new ObjectParameter("cons_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarVenta", cons_productoParameter, cantidadParameter);
        }
    }
}
