//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.inventario_det = new HashSet<inventario_det>();
            this.ventas_clientes_det = new HashSet<ventas_clientes_det>();
        }
    
        public int cons_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_producto { get; set; }
        public string imagen { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string unidad_medida { get; set; }
        public int existencia { get; set; }
        public int existenciamin { get; set; }
        public int existenciamax { get; set; }
        public bool estado { get; set; }
        public System.DateTime registro_prod { get; set; }
        public int cons_categoria { get; set; }
        public string tipo_mascota { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_det> inventario_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_clientes_det> ventas_clientes_det { get; set; }
    }
}
