//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDORES()
        {
            this.COMPRAS_PROVEEDORES_ENC = new HashSet<COMPRAS_PROVEEDORES_ENC>();
            this.PRODUCTO_PROVEED = new HashSet<PRODUCTO_PROVEED>();
        }
    
        public long ID_PROVEEDOR { get; set; }
        public long ID_USUARIO { get; set; }
        public string NUM_IDENTIFIC_PROVEED { get; set; }
        public string NOMBRE_PROVEED { get; set; }
        public string TELEFONO_PROVEED { get; set; }
        public string DIRECCION_PROVEED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS_PROVEEDORES_ENC> COMPRAS_PROVEEDORES_ENC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_PROVEED> PRODUCTO_PROVEED { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
