//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD_MEDIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIDAD_MEDIDA()
        {
            this.COMPRAS_PROVEEDORES_DET = new HashSet<COMPRAS_PROVEEDORES_DET>();
            this.INVENTARIO_DET = new HashSet<INVENTARIO_DET>();
            this.PRODUCTO_PROVEED = new HashSet<PRODUCTO_PROVEED>();
            this.VENTAS_CLIENTES_DET = new HashSet<VENTAS_CLIENTES_DET>();
        }
    
        public long ID_UNI_MEDIDA { get; set; }
        public string NOMBRE_UNI_MED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAS_PROVEEDORES_DET> COMPRAS_PROVEEDORES_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_DET> INVENTARIO_DET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_PROVEED> PRODUCTO_PROVEED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS_CLIENTES_DET> VENTAS_CLIENTES_DET { get; set; }
    }
}
