//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.carrito_enc = new HashSet<carrito_enc>();
            this.ventas_clientes_enc = new HashSet<ventas_clientes_enc>();
        }
    
        public int consecutivo { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string correoElectronico { get; set; }
        public string contrasenna { get; set; }
        public bool estado { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public int consecutivoRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrito_enc> carrito_enc { get; set; }
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_clientes_enc> ventas_clientes_enc { get; set; }
    }
}
