//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int consecutivo { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string correoElectronico { get; set; }
        public string contrasenna { get; set; }
        public bool estado { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public int consecutivoRol { get; set; }
    
        public virtual rol rol { get; set; }
    }
}
