//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS_CLIENTES_ENC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS_CLIENTES_ENC()
        {
            this.VENTAS_CLIENTES_DET = new HashSet<VENTAS_CLIENTES_DET>();
        }
    
        public long ID_VENTA { get; set; }
        public long ID_CLIENTE { get; set; }
        public System.DateTime FEC_VENTA { get; set; }
        public decimal MONTO_VENTA_BRUT { get; set; }
        public decimal IMPUESTO_VENTA_TOT { get; set; }
        public decimal MONTO_VENTA_NET { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS_CLIENTES_DET> VENTAS_CLIENTES_DET { get; set; }
    }
}
