//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_clientes_enc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ventas_clientes_enc()
        {
            this.ventas_clientes_det = new HashSet<ventas_clientes_det>();
        }
    
        public int cons_venta { get; set; }
        public int consecutivo { get; set; }
        public System.DateTime fec_venta { get; set; }
        public decimal monto_venta_brut { get; set; }
        public decimal impuesto_venta_tot { get; set; }
        public decimal monto_venta_net { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_clientes_det> ventas_clientes_det { get; set; }
    }
}
