//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS_CLIENTES_DET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS_CLIENTES_DET()
        {
            this.EVALUA_PROV = new HashSet<EVALUA_PROV>();
        }
    
        public long ID_VENTA_DET { get; set; }
        public long ID_VENTA { get; set; }
        public long ID_PRODUCTO { get; set; }
        public long ID_UNIDAD_MEDIDA { get; set; }
        public int CANTIDAD { get; set; }
        public decimal MONTO_LINEA { get; set; }
        public decimal IMPUESTO_LINEA { get; set; }
        public decimal MONTO_NETO_LINEA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUA_PROV> EVALUA_PROV { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
        public virtual VENTAS_CLIENTES_ENC VENTAS_CLIENTES_ENC { get; set; }
    }
}
