//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_clientes_det
    {
        public int cons_venta_det { get; set; }
        public int cons_venta { get; set; }
        public int cons_producto { get; set; }
        public int cantidad { get; set; }
        public decimal monto_linea { get; set; }
        public decimal impuesto_linea { get; set; }
        public decimal monto_neto_linea { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ventas_clientes_enc ventas_clientes_enc { get; set; }
    }
}
