//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalG1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_clientes_det
    {
        public int cons_venta_det { get; set; }
        public int cons_venta { get; set; }
        public int cons_producto { get; set; }
        public int cantidad { get; set; }
        public decimal monto_linea { get; set; }
        public decimal impuesto_linea { get; set; }
        public decimal monto_neto_linea { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ventas_clientes_enc ventas_clientes_enc { get; set; }
    }
}
